# Generated by Django 4.1.7 on 2023-03-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_curso_camada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
